# Generated by Django 3.1.2 on 2021-02-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('image', models.TextField(max_length=300)),
                ('release_date', models.TextField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(default='mobile')),
            ],
        ),
    ]
